# Generated by Django 4.2.26 on 2025-11-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('wechat_id', models.CharField(blank=True, max_length=50, verbose_name='微信号')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
        ),
    ]
