# Generated by Django 4.2.26 on 2025-11-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='这个人什么也没有写', verbose_name='个人简介'),
        ),
    ]
