# Generated by Django 4.2.26 on 2025-12-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师')], default='student', max_length=10, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_name',
            field=models.CharField(max_length=50, verbose_name='班级/部门'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号/工号'),
        ),
    ]
