# Generated by Django 4.2.26 on 2026-05-12 14:03

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=apps.user.models.avatar_upload_to,
                verbose_name="头像",
            ),
        ),
    ]
